extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern const GeoLayout wf_area_2_geo[];
extern const GeoLayout wf_area_2[];
extern const Collision wf_area_2_collision[];
extern const MacroObject wf_area_2_macro_objs[];
extern const GeoLayout wf_area_3_geo[];
extern const GeoLayout wf_area_3[];
extern const Collision wf_area_3_collision[];
extern const MacroObject wf_area_3_macro_objs[];
extern const GeoLayout wf_area_4_geo[];
extern const GeoLayout wf_area_4[];
extern const Collision wf_area_4_collision[];
extern const MacroObject wf_area_4_macro_objs[];
extern const GeoLayout wf_area_5_geo[];
extern const GeoLayout wf_area_5[];
extern const Collision wf_area_5_collision[];
extern const MacroObject wf_area_5_macro_objs[];
extern Lights1 wf_dl_gray_walls_lights;
extern Lights1 wf_dl_Timer_Start_lights;
extern Lights1 wf_dl_blue_walls_lights;
extern Lights1 wf_dl_goop_lights;
extern Lights1 wf_dl_InstantWarp_lights;
extern Lights1 wf_dl_f3dlite_material_001_lights;
extern Lights1 wf_dl_InstantWarp_a2_lights;
extern Lights1 wf_dl_InstantWarp_001_lights;
extern Lights1 wf_dl_InstantWarp_a4_lights;
extern Lights1 wf_dl_f3dlite_material_004_lights;
extern Lights1 wf_dl_f3dlite_material_003_lights;
extern u8 wf_dl_ventwalls_ci8[];
extern u8 wf_dl_ventwalls_pal_rgba16[];
extern u8 wf_dl_metal_ci8[];
extern u8 wf_dl_metal_pal_rgba16[];
extern u8 wf_dl_metal3_ci8[];
extern u8 wf_dl_metal3_pal_rgba16[];
extern u8 wf_dl_goop_ci8[];
extern u8 wf_dl_goop_pal_rgba16[];
extern u8 wf_dl_box2_ci8[];
extern u8 wf_dl_box2_pal_rgba16[];
extern u8 wf_dl_box1_ci8[];
extern u8 wf_dl_box1_pal_rgba16[];
extern Vtx wf_dl_Area_1_Mesh_mesh_layer_1_vtx_0[646];
extern Gfx wf_dl_Area_1_Mesh_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Area_1_Mesh_mesh_layer_1_vtx_1[6];
extern Gfx wf_dl_Area_1_Mesh_mesh_layer_1_tri_1[];
extern Vtx wf_dl_Area_1_Mesh_mesh_layer_1_vtx_2[600];
extern Gfx wf_dl_Area_1_Mesh_mesh_layer_1_tri_2[];
extern Vtx wf_dl_Area_1_Mesh_mesh_layer_1_vtx_3[75];
extern Gfx wf_dl_Area_1_Mesh_mesh_layer_1_tri_3[];
extern Vtx wf_dl_Area_1_Mesh_mesh_layer_1_vtx_4[4];
extern Gfx wf_dl_Area_1_Mesh_mesh_layer_1_tri_4[];
extern Vtx wf_dl_Death_Plane_1_mesh_layer_5_vtx_0[4];
extern Gfx wf_dl_Death_Plane_1_mesh_layer_5_tri_0[];
extern Vtx wf_dl_Area_2_Mesh_mesh_layer_1_vtx_0[421];
extern Gfx wf_dl_Area_2_Mesh_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Area_2_Mesh_mesh_layer_1_vtx_1[407];
extern Gfx wf_dl_Area_2_Mesh_mesh_layer_1_tri_1[];
extern Vtx wf_dl_Area_2_Mesh_mesh_layer_1_vtx_2[32];
extern Gfx wf_dl_Area_2_Mesh_mesh_layer_1_tri_2[];
extern Vtx wf_dl_Area_2_Mesh_mesh_layer_1_vtx_3[4];
extern Gfx wf_dl_Area_2_Mesh_mesh_layer_1_tri_3[];
extern Vtx wf_dl_Death_Plane_2_mesh_layer_5_vtx_0[4];
extern Gfx wf_dl_Death_Plane_2_mesh_layer_5_tri_0[];
extern Vtx wf_dl_Area_3_Mesh_mesh_layer_1_vtx_0[292];
extern Gfx wf_dl_Area_3_Mesh_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Area_3_Mesh_mesh_layer_1_vtx_1[198];
extern Gfx wf_dl_Area_3_Mesh_mesh_layer_1_tri_1[];
extern Vtx wf_dl_Area_3_Mesh_mesh_layer_1_vtx_2[40];
extern Gfx wf_dl_Area_3_Mesh_mesh_layer_1_tri_2[];
extern Vtx wf_dl_Area_3_Mesh_mesh_layer_1_vtx_3[4];
extern Gfx wf_dl_Area_3_Mesh_mesh_layer_1_tri_3[];
extern Vtx wf_dl_Death_Plane_3_mesh_layer_5_vtx_0[4];
extern Gfx wf_dl_Death_Plane_3_mesh_layer_5_tri_0[];
extern Vtx wf_dl_Area_4_Mesh_mesh_layer_1_vtx_0[130];
extern Gfx wf_dl_Area_4_Mesh_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Area_4_Mesh_mesh_layer_1_vtx_1[56];
extern Gfx wf_dl_Area_4_Mesh_mesh_layer_1_tri_1[];
extern Vtx wf_dl_Area_4_Mesh_mesh_layer_1_vtx_2[4];
extern Gfx wf_dl_Area_4_Mesh_mesh_layer_1_tri_2[];
extern Vtx wf_dl_Area_4_Mesh_mesh_layer_1_vtx_3[8];
extern Gfx wf_dl_Area_4_Mesh_mesh_layer_1_tri_3[];
extern Vtx wf_dl_Death_Plane_4_mesh_layer_5_vtx_0[4];
extern Gfx wf_dl_Death_Plane_4_mesh_layer_5_tri_0[];
extern Vtx wf_dl_Area_5_Mesh_mesh_layer_1_vtx_0[44];
extern Gfx wf_dl_Area_5_Mesh_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Area_5_Mesh_mesh_layer_1_vtx_1[44];
extern Gfx wf_dl_Area_5_Mesh_mesh_layer_1_tri_1[];
extern Vtx wf_dl_Area_5_Mesh_mesh_layer_1_vtx_2[256];
extern Gfx wf_dl_Area_5_Mesh_mesh_layer_1_tri_2[];
extern Vtx wf_dl_Area_5_Mesh_mesh_layer_1_vtx_3[180];
extern Gfx wf_dl_Area_5_Mesh_mesh_layer_1_tri_3[];
extern Vtx wf_dl_Death_Plane_5_mesh_layer_5_vtx_0[4];
extern Gfx wf_dl_Death_Plane_5_mesh_layer_5_tri_0[];
extern Gfx mat_wf_dl_gray_walls[];
extern Gfx mat_revert_wf_dl_gray_walls[];
extern Gfx mat_wf_dl_Timer_Start[];
extern Gfx mat_revert_wf_dl_Timer_Start[];
extern Gfx mat_wf_dl_blue_walls[];
extern Gfx mat_revert_wf_dl_blue_walls[];
extern Gfx mat_wf_dl_goop[];
extern Gfx mat_revert_wf_dl_goop[];
extern Gfx mat_wf_dl_InstantWarp[];
extern Gfx mat_revert_wf_dl_InstantWarp[];
extern Gfx mat_wf_dl_f3dlite_material_001[];
extern Gfx mat_wf_dl_InstantWarp_a2[];
extern Gfx mat_revert_wf_dl_InstantWarp_a2[];
extern Gfx mat_wf_dl_InstantWarp_001[];
extern Gfx mat_revert_wf_dl_InstantWarp_001[];
extern Gfx mat_wf_dl_InstantWarp_a4[];
extern Gfx mat_revert_wf_dl_InstantWarp_a4[];
extern Gfx mat_wf_dl_f3dlite_material_004[];
extern Gfx mat_revert_wf_dl_f3dlite_material_004[];
extern Gfx mat_wf_dl_f3dlite_material_003[];
extern Gfx mat_revert_wf_dl_f3dlite_material_003[];
extern Gfx wf_dl_Area_1_Mesh_mesh_layer_1[];
extern Gfx wf_dl_Death_Plane_1_mesh_layer_5[];
extern Gfx wf_dl_Area_2_Mesh_mesh_layer_1[];
extern Gfx wf_dl_Death_Plane_2_mesh_layer_5[];
extern Gfx wf_dl_Area_3_Mesh_mesh_layer_1[];
extern Gfx wf_dl_Death_Plane_3_mesh_layer_5[];
extern Gfx wf_dl_Area_4_Mesh_mesh_layer_1[];
extern Gfx wf_dl_Death_Plane_4_mesh_layer_5[];
extern Gfx wf_dl_Area_5_Mesh_mesh_layer_1[];
extern Gfx wf_dl_Death_Plane_5_mesh_layer_5[];
